[build]
  base = "client"
  publish = "client/build"
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://docify-grtclueyk-kratikakgs-projects.vercel.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
